### ISSUE TITLE
Rod doesn't use chromedp

### ISSUE THREAD

**Issue by ysmood** [rusq/slackauth#7]
The readme of this project says:

> The advantage over the Playwright is that rod uses chromedp, which is faster and does not require nodejs. The drawback is that it can’t use Firefox.

But Rod doesn't use chromedp, it uses cdp directly.

**Comment by rusq** [comment]
Hey @ysmood , I meant to write CDP, thanks for noticing, and thanks for rod library as well ;)

**Comment by rusq** [comment]
✅
